import { loadEnv } from 'vite';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fetchDungeonsFromNotion } from '../server/notion-fetch.mjs';

const env = loadEnv(process.env.NODE_ENV || 'development', process.cwd(), '');
const notionToken = env.NOTION_TOKEN;
const notionDatabaseId = env.NOTION_DATABASE_ID;

if (!notionToken || !notionDatabaseId) {
  throw new Error('Missing Notion env vars. Expected NOTION_TOKEN and NOTION_DATABASE_ID.');
}

async function main() {
  const dungeons = await fetchDungeonsFromNotion(notionToken, notionDatabaseId);
  const outputPath = path.resolve(process.cwd(), 'src/data/notion-dungeons.ts');
  const fileContent = `import type { Dungeon } from '../types';\n\n// Generated by scripts/sync-notion.mjs — do not edit manually\nexport const dungeons: Dungeon[] = ${JSON.stringify(dungeons, null, 2)};\n`;

  await writeFile(outputPath, fileContent, 'utf8');
  console.log(`Synced ${dungeons.length} dungeons from Notion.`);
}

main().catch((error) => {
  if (error?.code === 'object_not_found') {
    console.error('Notion sync failed: the configured database is not accessible to this integration.');
    console.error('Share the database with your Notion integration and confirm the database/data source ID in .env.');
  }
  console.error(error);
  process.exit(1);
});
