import { loadEnv } from 'vite';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { OVERVIEW_DATABASE_ENV_HINT, getNotionIndexSources } from '../server/notion-config.mjs';
import { fetchContentFromNotion } from '../server/notion-fetch.mjs';

const env = loadEnv(process.env.NODE_ENV || 'development', process.cwd(), '');
const notionToken = env.NOTION_TOKEN;
const notionIndexSources = getNotionIndexSources(env);

function getMissingEnvVars() {
  const missing = [];

  if (!notionToken) {
    missing.push('NOTION_TOKEN');
  }

  if (notionIndexSources.length === 0) {
    missing.push(OVERVIEW_DATABASE_ENV_HINT);
  }

  return missing;
}

const missingEnvVars = getMissingEnvVars();

if (missingEnvVars.length > 0) {
  throw new Error(
    `Missing Notion env vars: ${missingEnvVars.join(', ')}`
  );
}

async function main() {
  const dungeons = await fetchContentFromNotion(notionToken, notionIndexSources);
  const outputPath = path.resolve(process.cwd(), 'src/data/notion-dungeons.ts');
  const fileContent = `import type { Dungeon } from '../types';\n\n// Generated by scripts/sync-notion.mjs — do not edit manually\nexport const dungeons: Dungeon[] = ${JSON.stringify(dungeons, null, 2)};\n`;

  await writeFile(outputPath, fileContent, 'utf8');
  console.log(`Synced ${dungeons.length} entries from Notion.`);
}

main().catch((error) => {
  if (error?.code === 'object_not_found') {
    console.error('Notion sync failed: one of the configured databases is not accessible to this integration.');
    console.error('Share each overview and detail database with your Notion integration and confirm the database IDs in .env.');
  }
  console.error(error);
  process.exit(1);
});
