import type { Dungeon } from '../types';

// Generated by scripts/sync-notion.mjs — do not edit manually
export const dungeons: Dungeon[] = [
  {
    "id": "algethar-academy",
    "section": "mythicplus",
    "name": "Algeth'ar Academy",
    "summary": "",
    "editUrl": "https://www.notion.so/Algeth-ar-Academy-32e26030e30c80e2a062dfb973db09e3",
    "trashNotes": {
      "name": "Trash Notes",
      "summary": "",
      "mechanics": [],
      "tags": []
    },
    "bosses": [
      {
        "name": "Overgrown Ancient",
        "summary": "Add-centric nature boss with group movement, bleed cleanses, and lasher-control bursts.",
        "mechanics": [
          {
            "text": "Stay stacked and move together during Germinate so spawned adds stay clumped for efficient cleave.",
            "tags": []
          },
          {
            "text": "Swap to Ancient Branch, interrupt Healing Touch, and use its Abundance circle to clear Splinterbark bleeds.",
            "tags": []
          },
          {
            "text": "At Burst Forth, pick up Hungry Lashers immediately, rotate poison dispels on Lasher Toxin, kite if necessary, and respect Barkbreaker if adds are still alive.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Crawth",
        "summary": "Arena boss with tank pressure, frontal dodges, and scripted goal intermissions.",
        "mechanics": [
          {
            "text": "Use tank defensives for Savage Peck and keep spread enough that Deafening Screech splash plus DoT do not overwhelm the party.",
            "tags": []
          },
          {
            "text": "Sidestep Overpowering Gust and hold stable positioning until Ruinous Winds starts at 75% and 45%.",
            "tags": []
          },
          {
            "text": "Throw three balls into the chosen goal to interrupt Ruinous Winds, then play around the permanent arena effect from that goal for the rest of the fight.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Vexamus",
        "summary": "Orb-soak arcane fight with frontal management, bomb placement, and energy bursts.",
        "mechanics": [
          {
            "text": "Spread for Arcane Orbs and assign soaks so no player over-stacks Oversurge or lets an orb reach the boss.",
            "tags": []
          },
          {
            "text": "Tanks point Arcane Expulsion away from the group and Mana Bomb targets move their puddles toward the room edge.",
            "tags": []
          },
          {
            "text": "At full energy, brace for Arcane Fissure knockback and keep moving through the follow-up circles without dropping back into old puddles.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Echo of Doragosa",
        "summary": "Chaotic arcane finale with immediate opener damage, rift control, and combo-hit punishment.",
        "mechanics": [
          {
            "text": "Enter topped for the opening Unleash Energy, pull toward the entrance, and build your first Arcane Rifts where they will not choke the room.",
            "tags": []
          },
          {
            "text": "Avoid feeding Overwhelming Power stacks, because three stacks create another Arcane Rift under you and can snowball the arena.",
            "tags": []
          },
          {
            "text": "Stay loosely spread for Energy Bomb, watch for Arcane Missiles overlap, and use personals whenever those hits line up with existing rift pressure.",
            "tags": []
          }
        ],
        "tags": []
      }
    ],
    "trash": []
  },
  {
    "id": "magisters-terrace",
    "section": "mythicplus",
    "name": "Magisters' Terrace",
    "summary": "",
    "editUrl": "https://www.notion.so/Magisters-Terrace-32e26030e30c8042aefee2a854232e18",
    "bosses": [
      {
        "name": "Arcanotron Custos",
        "summary": "Arcane space-control boss with knockbacks, dispels, and an orb-soak refuel phase.",
        "mechanics": [
          {
            "text": "Use the room edges for Arcane Expulsion puddles, keep Ethereal Shackles dispelled or freedomed, and brace for Repulsing Slam knockbacks.",
            "tags": []
          },
          {
            "text": "At Refueling Protocol, spread loosely to soak Energy Orbs without over-stacking Unstable Energy, even as more puddles spawn.",
            "tags": []
          },
          {
            "text": "As floor space disappears, overlap safe puddle placements, save personals for bad Shackles plus Expulsion overlap, and keep the boss moved out of melee clutter.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Seranel Sunlash",
        "summary": "Control-heavy caster fight built around mark clears, buff removal, and silence-zone timing.",
        "mechanics": [
          {
            "text": "Keep Suppression Zone near the center so marked players can clear Runic Mark without boxing the team into dead space.",
            "tags": []
          },
          {
            "text": "Clear Runic Mark one at a time with enough spacing to avoid double Null Reaction hits, and use a personal on the later clear if needed.",
            "tags": []
          },
          {
            "text": "Purge Hastening Ward whenever possible and step into Suppression Zone just before Wave of Silence lands to avoid the long pacify.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Gemellus",
        "summary": "Clone encounter that ramps at 50% and punishes missed links, puddle placement, and pull-ins.",
        "mechanics": [
          {
            "text": "On pull and again at 50%, cleave every Triplicate clone because they share health and each clone pressures a different player.",
            "tags": []
          },
          {
            "text": "Drop Cosmic Sting puddles away from the fighting lane and immediately run Neural Link into your assigned clone to remove both the debuff and the boss shield.",
            "tags": []
          },
          {
            "text": "Pre-move for Astral Grasp, outrun the pull if targeted, and dodge the clone circles that appear at the same time.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Degentrius",
        "summary": "Pizza-slice void fight with orb passing, beam denial, and tank debuff management.",
        "mechanics": [
          {
            "text": "Split the group around the room so every Unstable Void Essence pass has a receiver and no one drops the ball, or Void Destruction stacks will spiral the fight.",
            "tags": []
          },
          {
            "text": "Never cross the Void Torrent beam walls, and keep track of which slice each player is covering before the next pass begins.",
            "tags": []
          },
          {
            "text": "Tanks point Hulking Fragment away from allies, back out for dispels, and place Umbral Splinters or Stygian Ichor away from melee paths.",
            "tags": []
          }
        ],
        "tags": []
      }
    ],
    "trash": []
  },
  {
    "id": "maisara-caverns",
    "section": "mythicplus",
    "name": "Maisara Caverns",
    "summary": "",
    "editUrl": "https://www.notion.so/Maisara-Caverns-32e26030e30c800796d8fc3bebd95ccc",
    "trashNotes": {
      "name": "Trash Notes",
      "summary": "",
      "mechanics": [
        {
          "text": "Do only necessary ones for Quest, there are more than enough mobs",
          "tags": []
        }
      ],
      "tags": []
    },
    "bosses": [
      {
        "name": "Muro'jin & Nekraxx",
        "summary": "Dual-boss opener that demands even health, trap routing, and disease-aware defensive play.",
        "mechanics": [
          {
            "text": "Use Bloodlust at the beginning",
            "tags": []
          },
          {
            "text": "Kill Bosses at the same time, otherwise they get boosts",
            "tags": []
          },
          {
            "text": "When Nekraxx has red arrow on you and charges towards you stand behind a trap",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Vordaza",
        "summary": "Attrition boss with phantom collisions, tank channels, frontal dodges, and shield breaks.",
        "mechanics": [
          {
            "text": "Kite Wrest Phantoms into each other in pairs, never detonate too many at once, and avoid standing in the pools they leave behind.",
            "tags": []
          },
          {
            "text": "Tanks use defensives for Drain Soul and the group saves damage to break Necrotic Convergence before the channel resolves.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Rak'tul, Vessel of Souls",
        "summary": "Final soul boss with constant aura damage, grouped totem spawns, and tank knockback combos.",
        "mechanics": [
          {
            "text": "Use Bloodlust at the beginning",
            "tags": []
          },
          {
            "text": "Tank to the wall and use movement to get out of pools",
            "tags": []
          },
          {
            "text": "During Crush Souls, the three targets group tightly so Soulbind Totems spawn together, then the party swaps to destroy the totems before the pull effect spirals.",
            "tags": []
          },
          {
            "text": "When knocked back as a ghost, run towards boss and dodge ghosts",
            "tags": []
          }
        ],
        "tags": []
      }
    ],
    "trash": []
  },
  {
    "id": "nexus-point-xenas",
    "section": "mythicplus",
    "name": "Nexus-Point Xenas",
    "summary": "",
    "editUrl": "https://www.notion.so/Nexus-Point-Xenas-32e26030e30c80e599e1c9ddde458d2d",
    "bosses": [
      {
        "name": "Chief Corewright Kasreth",
        "summary": "Arcane control fight with beam shutdowns, puddle baiting, and absorb-heavy detonations.",
        "mechanics": [
          {
            "text": "Don’t Step in beam unless you have Blue Arrow (Stand in crossed beams to disable as many beams as possible.",
            "tags": []
          },
          {
            "text": "Bait puddles to the room edge, and prepare healer cooldowns for the detonation hit plus healing absorb.",
            "tags": []
          },
          {
            "text": "When boss knocks back don’t let him kick you into beams",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Corewarden Nysarra",
        "summary": "Void miniboss fight with debuffed players, dangerous summoned adds, and burst-vulnerable phases.",
        "mechanics": [
          {
            "text": "Spread Mechanic",
            "tags": []
          },
          {
            "text": "On Null Vanguard, interrupt Nullify, point Dreadflail's Void Lash away from the group, and kill the add pack before it overruns the arena.",
            "tags": []
          },
          {
            "text": "Tanks hold a defensive for Umbral Lash while the group pushes the Lightscar Flare damage window once adds are under control.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Lothraxion",
        "summary": "Image-management final boss with permanent puddles, targeted bursts, and roaming clone hazards.",
        "mechanics": [
          {
            "text": "Tanks use defensives for Searing Rend and drop its permanent puddles where future movement will stay clear.",
            "tags": []
          },
          {
            "text": "Brilliant Dispersion targets spread, use personals for the DoT, and then avoid every Fractured Image they leave behind.",
            "tags": []
          },
          {
            "text": "Watch for Clones which move in the direction of their beams",
            "tags": []
          },
          {
            "text": "When boss splits up and hides, search and interrupt the one without Horns",
            "tags": []
          }
        ],
        "tags": []
      }
    ],
    "trash": []
  },
  {
    "id": "pit-of-saron",
    "section": "mythicplus",
    "name": "Pit of Saron",
    "summary": "",
    "editUrl": "https://www.notion.so/Pit-of-Saron-32e26030e30c80bbacdfc08d031a6661",
    "bosses": [
      {
        "name": "Forgemaster Garfrost",
        "summary": "Ore-chunk management fight with targeted circles, anti-stun tank play, and hide phases.",
        "mechanics": [
          {
            "text": "Spread Throw Saronite circles so Ore Chunks and the puddles they leave do not wall off the arena.",
            "tags": []
          },
          {
            "text": "Tanks use Orebreaker on an Ore Chunk to break it and avoid the stun while still mitigating the hit.",
            "tags": []
          },
          {
            "text": "Hide behind the last chunk for Glacial Overload, then dispel Cryostomp targets quickly to reduce Siphoning Chill damage.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Ick & Krick",
        "summary": "Shared-health duo with add cleave, interrupt priority, puddle placement, and fixate kiting.",
        "mechanics": [
          {
            "text": "Cleave both bosses because Necrolink shares health, then interrupt Krick's Death Bolt while controlling Shades from Shade Shift.",
            "tags": []
          },
          {
            "text": "Use freedoms or curse dispels on Shadowbind, drop Blight Smash and Plague Explosion puddles out of traffic, and use tank cooldowns for Blight Smash.",
            "tags": []
          },
          {
            "text": "During Get 'em, Ick!, the fixated player kites cleanly for the full chase while the rest of the group maximizes boss and add cleave.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Scourgelord Tyrannus",
        "summary": "Bone-pile final boss with target marking, add-wave triage, and layered ground denial.",
        "mechanics": [
          {
            "text": "Aim Rime Blast through marked Bone Piles to prepare cleaner Army of the Dead spawns later in the fight.",
            "tags": []
          },
          {
            "text": "On Army of the Dead, tank Rotlings carefully, dispel Rotting Strikes as needed, and swap hard to Plaguespreaders while interrupting Plague Bolt and stabilizing Festering Pulse.",
            "tags": []
          },
          {
            "text": "Tanks use a defensive for Scourgelord's Brand and move to avoid the follow-up leap, while everyone sidesteps Death's Grasp and Ice Barrage circles.",
            "tags": []
          }
        ],
        "tags": []
      }
    ],
    "trash": []
  },
  {
    "id": "seat-of-the-triumvirate",
    "section": "mythicplus",
    "name": "Seat of the Triumvirate",
    "summary": "",
    "editUrl": "https://www.notion.so/Seat-of-the-Triumvirate-32e26030e30c80b4b70cd91fdd0d733a",
    "bosses": [
      {
        "name": "Zuraal the Ascended",
        "summary": "Single-target encounter with stacking spatial pressure and repeated void zones.",
        "mechanics": [
          {
            "text": "Phase 1: stack for split damage and rotate defensives during burst windows.",
            "tags": [
              "Healer",
              "Defensive"
            ]
          },
          {
            "text": "Move out of collapsing void zones before they cut off the room.",
            "tags": [
              "Dodge"
            ]
          },
          {
            "text": "Keep the boss centered so the group has space for later overlaps.",
            "tags": [
              "Tank"
            ]
          }
        ],
        "tags": [
          "Healer",
          "Defensive",
          "Dodge",
          "Tank"
        ]
      },
      {
        "name": "L'ura",
        "summary": "Final boss with heavy group damage and strict movement discipline.",
        "mechanics": [
          {
            "text": "Spread cleanly for orb patterns, then collapse quickly for healing throughput windows.",
            "tags": [
              "Dodge",
              "Healer"
            ]
          },
          {
            "text": "Use personals during the late burn when void damage ramps sharply.",
            "tags": [
              "Defensive"
            ]
          },
          {
            "text": "Keep the edge of the room clear so movement paths stay open.",
            "tags": [
              "Dodge"
            ]
          }
        ],
        "tags": [
          "Dodge",
          "Healer",
          "Defensive"
        ]
      },
      {
        "name": "Viceroy Nezhar",
        "summary": "Controlled positioning check with punishing frontal and spread mechanics.",
        "mechanics": [
          {
            "text": "Face the boss away and keep the group out of the frontal cone.",
            "tags": [
              "Tank"
            ]
          },
          {
            "text": "Reposition early for overlapping ground effects.",
            "tags": [
              "Dodge"
            ]
          },
          {
            "text": "Use personals before heavy burst overlaps if space gets tight.",
            "tags": [
              "Defensive"
            ]
          }
        ],
        "tags": [
          "Tank",
          "Dodge",
          "Defensive"
        ]
      },
      {
        "name": "Saprish",
        "summary": "Add-control encounter with stealth threats and priority target swaps.",
        "mechanics": [
          {
            "text": "Focus the highest threat add before committing to cleave.",
            "tags": [
              "Priority Target",
              "DPS"
            ]
          },
          {
            "text": "Interrupt dangerous casts from supporting mobs.",
            "tags": [
              "Kick"
            ]
          },
          {
            "text": "Reposition early when stealth mechanics collapse on the group.",
            "tags": [
              "Dodge"
            ]
          }
        ],
        "tags": [
          "Priority Target",
          "DPS",
          "Kick",
          "Dodge"
        ]
      }
    ],
    "trash": []
  },
  {
    "id": "skyreach",
    "section": "mythicplus",
    "name": "Skyreach",
    "summary": "",
    "editUrl": "https://www.notion.so/Skyreach-32e26030e30c8053ab60c8502be4e369",
    "bosses": [
      {
        "name": "Ranjit",
        "summary": "Platform fight with wind-orb placement, bleed bursts, and returning chakram paths.",
        "mechanics": [
          {
            "text": "Place Gale Surge wind orbs where they will not block later movement or knock players off the platform.",
            "tags": []
          },
          {
            "text": "Heal or cleanse Fan of Blades bleeds aggressively and use personals if the same players are targeted in back-to-back cycles.",
            "tags": []
          },
          {
            "text": "Track both the outbound and returning path of Wind Chakram while sidestepping Chakram Vortex tornadoes and preserving safe lanes.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Araknath",
        "summary": "Stationary construct fight centered on intercept beams and energy-based burst windows.",
        "mechanics": [
          {
            "text": "Keep a tank in melee to stop Blast Wave, but respect the small Defensive Protocol zone under the boss.",
            "tags": []
          },
          {
            "text": "Non-tanks intercept Energize beams from Lesser Constructs, while the tank points Fiery Smash away from beam-soakers and then dodges Heart Exhaustion.",
            "tags": []
          },
          {
            "text": "If any Energize beams connect, prepare group defensives for a much harder Supernova at full energy.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Rukhran",
        "summary": "Stationary bird boss with fixate add control, egg placement, and pillar-hide checks.",
        "mechanics": [
          {
            "text": "Swap instantly to the Sunwing from Sunbreak, kite Burning Pursuit cleanly, and never kill the add on top of eggs or it will respawn.",
            "tags": []
          },
          {
            "text": "Tanks stay in range to stop Screech, but the whole group must hide behind the pillar for every Searing Quills cast.",
            "tags": []
          },
          {
            "text": "Return to the boss quickly after each hide and use tank defensives on every Burning Claws.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "High Sage Viryx",
        "summary": "Final platform boss with rescue checks, chase-beam placement, and mandatory interrupts.",
        "mechanics": [
          {
            "text": "Heal Scorching Ray targets aggressively and use personals if repeat beams stack on the same players.",
            "tags": []
          },
          {
            "text": "When Cast Down grabs a player, they run toward the entrance while the group swaps, stuns, and slows the add before the victim is thrown away.",
            "tags": []
          },
          {
            "text": "Kite Lens Flare to the platform edges, avoid its fire trail, and keep Solar Blast interrupted to reduce tank damage.",
            "tags": []
          }
        ],
        "tags": []
      }
    ],
    "trash": []
  },
  {
    "id": "windrunner-spire",
    "section": "mythicplus",
    "name": "Windrunner Spire",
    "summary": "",
    "editUrl": "https://www.notion.so/Windrunner-Spire-32e26030e30c80dea288e4d8b433dee4",
    "trashNotes": {
      "name": "Trash Notes",
      "summary": "",
      "mechanics": [
        {
          "text": "Use Bloodlust on first pull",
          "tags": []
        }
      ],
      "tags": []
    },
    "bosses": [
      {
        "name": "Emberdawn",
        "summary": "Fire platform boss with debuff puddles, high-damage intermissions, and rotating frontal sweeps.",
        "mechanics": [
          {
            "text": "Flaming Updraft targets move to the outer rim so their puddles and later Flaming Twisters do not cut the center of the platform.",
            "tags": []
          },
          {
            "text": "During Burning Gale, heal through the raid damage while dodging spawned twisters and the rotating Fire Breath frontals.",
            "tags": []
          },
          {
            "text": "As floor space shrinks, keep safe outer placements disciplined so the next gale cycle still leaves clean lanes.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Derelict Duo",
        "summary": "Two-target undead fight with simultaneous-kill pressure, interrupt checks, and forced line play.",
        "mechanics": [
          {
            "text": "Keep both bosses even, because Broken Bond on the survivor becomes unmanageable if one dies early.",
            "tags": []
          },
          {
            "text": "Interrupt Shadow Bolt, dispel or out-range Curse of Darkness, and use crowd control to stop the Dark Entity if the curse cannot be removed.",
            "tags": []
          },
          {
            "text": "When Debilitating Shriek overlaps Heaving Yank, the yanked player runs behind Kalis to stop the group blast while the team keeps both bosses close for cleave.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "Commander Kroluk",
        "summary": "Leap-baiting commander fight with fear checks, tank channels, and add-cleave positioning.",
        "mechanics": [
          {
            "text": "Designate the furthest player to bait the first Reckless Leap, then let the tank bait the second while everyone dodges Falling Rubble.",
            "tags": []
          },
          {
            "text": "Pair up or stack in small groups for Intimidating Shout so nobody gets feared out of position.",
            "tags": []
          },
          {
            "text": "Tanks use defensives for Rampage, keep spawned adds stacked for cleave, and heal Rallying Bellow plus leap damage before the next sequence.",
            "tags": []
          }
        ],
        "tags": []
      },
      {
        "name": "The Restless Heart",
        "summary": "Arrow-driven finale where the group clears stacks and times aerial dodges to survive wind mechanics.",
        "mechanics": [
          {
            "text": "[Phase 1]",
            "tags": []
          },
          {
            "text": "Use Bloodlust at the beginning of the fight.",
            "tags": []
          },
          {
            "text": "Dodge Arrow Rain while using Turbulent Arrows to remove Squall Leap stacks before they become unmanageable.",
            "tags": []
          },
          {
            "text": "Pre-position for Bullseye Windblast and Billowing Wind so the group does not double up on the same arrow and lose a safe launch point.",
            "tags": []
          },
          {
            "text": "Tanks can use an arrow to cancel Tempest Slash knockback while also clearing their own stacks, and the party should use personals for Bolt Gale.",
            "tags": []
          }
        ],
        "tags": []
      }
    ],
    "trash": []
  }
];
