import type { Dungeon } from '../types';

// Generated by scripts/sync-notion.mjs — do not edit manually
export const dungeons: Dungeon[] = [
  {
    "id": "seat-of-the-triumvirate",
    "section": "mythicplus",
    "name": "The Seat of the Triumvirate",
    "summary": "Eredar stronghold on Argus. Void corruption and spreading mechanics demand strict group positioning.",
    "expansion": "Legion",
    "bosses": [
      {
        "name": "Zuraal the Ascended",
        "summary": "Single-target encounter with stacking spatial pressure and repeated void zones.",
        "mechanics": [
          {
            "text": "Phase 1: stack for split damage and rotate defensives during burst windows.",
            "tags": [
              "Defensive",
              "Healer"
            ]
          },
          {
            "text": "Move out of collapsing void zones before they cut off the room.",
            "tags": [
              "Dodge"
            ]
          },
          {
            "text": "Keep the boss centered so the group has space for later overlaps.",
            "tags": [
              "Tank"
            ]
          }
        ],
        "tags": [
          "Defensive",
          "Healer",
          "Dodge",
          "Tank"
        ],
        "priority": "High"
      },
      {
        "name": "L'ura",
        "summary": "Final boss with heavy group damage and strict movement discipline.",
        "mechanics": [
          {
            "text": "Spread cleanly for orb patterns, then collapse quickly for healing throughput windows.",
            "tags": [
              "Dodge",
              "Healer"
            ]
          },
          {
            "text": "Use personals during the late burn when void damage ramps sharply.",
            "tags": [
              "Defensive"
            ]
          }
        ],
        "tags": [
          "Dodge",
          "Healer",
          "Defensive"
        ],
        "priority": "High"
      }
    ],
    "trash": [
      {
        "name": "Shadowguard Voidbender",
        "summary": "Dangerous caster pack that can quickly overwhelm the group if left unchecked.",
        "mechanics": [
          {
            "text": "Interrupt Void Bolt whenever possible.",
            "tags": [
              "Kick"
            ]
          },
          {
            "text": "Step out of dropped void zones before the next cast overlaps them.",
            "tags": [
              "Dodge"
            ]
          }
        ],
        "tags": [
          "Kick",
          "Dodge"
        ],
        "priority": "High"
      },
      {
        "name": "Shadowguard Riftstalker",
        "summary": "Mobile threat that creates chaos if it is not focused quickly.",
        "mechanics": [
          {
            "text": "Focus this mob first when it is paired with dangerous caster packs.",
            "tags": [
              "Priority Target",
              "DPS"
            ]
          }
        ],
        "tags": [
          "Priority Target",
          "DPS"
        ],
        "priority": "Medium"
      }
    ]
  },
  {
    "id": "skyreach",
    "section": "mythicplus",
    "name": "Skyreach",
    "summary": "Arrakoa citadel in the Spires of Arak. Deadly Solar Winds and feather mechanics require constant movement.",
    "expansion": "Warlords of Draenor",
    "bosses": [],
    "trash": []
  },
  {
    "id": "magisters-terrace",
    "section": "mythicplus",
    "name": "Magisters' Terrace",
    "summary": "Blood elf citadel on the Isle of Quel'Danas. Heavy arcane interrupt checks and tight positioning throughout.",
    "expansion": "The Burning Crusade",
    "bosses": [],
    "trash": []
  },
  {
    "id": "nerubar-palace",
    "section": "raids",
    "name": "Nerub-ar Palace",
    "summary": "Raid encounter collection for structured boss plans and phase checklists.",
    "expansion": "The War Within",
    "bosses": [],
    "trash": []
  },
  {
    "id": "earthcrawl-mines",
    "section": "delves",
    "name": "Earthcrawl Mines",
    "summary": "Starter delve entry for compact route notes and priority pulls.",
    "expansion": "The War Within",
    "bosses": [],
    "trash": []
  }
];
