import type { Dungeon } from '../types';

// Generated by scripts/sync-notion.mjs � do not edit manually
export const dungeons: Dungeon[] = [
  {
    "id": "magisters-terrace",
    "name": "Magisters' Terrace",
    "summary": "Blood elf citadel on the Isle of Quel'Danas. Heavy arcane interrupt checks and tight positioning throughout.",
    "bosses": [],
    "trash": []
  },
  {
    "id": "maisara-caverns",
    "name": "Maisara Caverns",
    "summary": "Deep subterranean cavern system with heavy bleed, stacking debuffs and rapid patrol density.",
    "bosses": [],
    "trash": []
  },
  {
    "id": "nexus-point-xenas",
    "name": "Nexus-Point Xenas",
    "summary": "Fractured interdimensional waypoint. Phase-shift and spatial displacement mechanics make positioning critical.",
    "bosses": [],
    "trash": []
  },
  {
    "id": "windrunner-spire",
    "name": "Windrunner Spire",
    "summary": "The ancient spire of House Windrunner. Wind and movement mechanics heavily punish static positioning.",
    "bosses": [],
    "trash": []
  },
  {
    "id": "algethar-academy",
    "name": "Algeth'ar Academy",
    "summary": "Dracthyr academy in the Azure Span. Arcane puzzle mechanics and aggressive add management are key.",
    "bosses": [],
    "trash": []
  },
  {
    "id": "seat-of-the-triumvirate",
    "name": "The Seat of the Triumvirate",
    "summary": "Eredar stronghold on Argus. Void corruption and spreading mechanics demand strict group positioning.",
    "bosses": [
      {
        "name": "L’ura",
        "summary": "",
        "mechanics": [
          {
            "text": "Use cooldowns during intense damage phases",
            "tags": [
              "Defensive",
              "Healer"
            ]
          },
          {
            "text": "Avoid void zones and spreading damage effects",
            "tags": [
              "Dodge"
            ]
          },
          {
            "text": "Soak mechanics correctly to prevent group wipe",
            "tags": []
          },
          {
            "text": "Position carefully to avoid overlapping mechanics",
            "tags": []
          }
        ],
        "tags": [
          "Defensive",
          "Healer",
          "Dodge"
        ],
        "priority": "High"
      },
      {
        "name": "Zuraal the Ascended",
        "summary": "",
        "mechanics": [
          {
            "text": "Stack to split damage from major ability",
            "tags": [
              "Dodge"
            ]
          },
          {
            "text": "Use defensives during heavy damage phases",
            "tags": [
              "Defensive",
              "Healer"
            ]
          },
          {
            "text": "Move out of void zones on the ground",
            "tags": [
              "Dodge"
            ]
          },
          {
            "text": "Avoid standing alone during group damage abilities",
            "tags": []
          }
        ],
        "tags": [
          "Dodge",
          "Defensive",
          "Healer"
        ],
        "priority": "High"
      },
      {
        "name": "Viceroy Nezhar",
        "summary": "",
        "mechanics": [
          {
            "text": "Avoid frontal cone attacks from boss",
            "tags": [
              "Dodge"
            ]
          },
          {
            "text": "Use defensives during heavy burst phases",
            "tags": [
              "Defensive"
            ]
          },
          {
            "text": "Spread during group damage mechanics",
            "tags": []
          },
          {
            "text": "Manage space to avoid overlapping abilities",
            "tags": []
          }
        ],
        "tags": [
          "Dodge",
          "Defensive"
        ],
        "priority": "High"
      },
      {
        "name": "Saprish",
        "summary": "",
        "mechanics": [
          {
            "text": "Focus priority targets instead of cleaving everything",
            "tags": [
              "DPS"
            ]
          },
          {
            "text": "Kill adds quickly before they overwhelm the group",
            "tags": [
              "DPS",
              "Priority Target"
            ]
          },
          {
            "text": "Interrupt dangerous casts from adds",
            "tags": [
              "Kick"
            ]
          },
          {
            "text": "Watch for stealth mechanics and reposition carefully",
            "tags": [
              "Dodge"
            ]
          }
        ],
        "tags": [
          "DPS",
          "Priority Target",
          "Kick",
          "Dodge"
        ],
        "priority": "High"
      }
    ],
    "trash": [
      {
        "name": "Void Discharge Packs",
        "summary": "Use interrupts on dangerous casts",
        "mechanics": [],
        "tags": [
          "Kick"
        ],
        "priority": "High"
      },
      {
        "name": "Shadowguard Voidbender",
        "summary": "Avoid standing in void zones",
        "mechanics": [],
        "tags": [
          "Dodge"
        ],
        "priority": "Medium"
      },
      {
        "name": "Shadowguard Riftstalker",
        "summary": "Focus down quickly to reduce chaos",
        "mechanics": [],
        "tags": [
          "DPS"
        ],
        "priority": "Medium"
      },
      {
        "name": "Void Discharge Packs",
        "summary": "Avoid overlapping ground effects",
        "mechanics": [],
        "tags": [
          "Dodge"
        ],
        "priority": "High"
      },
      {
        "name": "Shadowguard Riftstalker",
        "summary": "Watch for teleport attacks and reposition",
        "mechanics": [],
        "tags": [
          "Dodge"
        ],
        "priority": "Medium"
      },
      {
        "name": "Shadowguard Voidbender",
        "summary": "Interrupt Void Bolt casts",
        "mechanics": [],
        "tags": [
          "Kick"
        ],
        "priority": "High"
      }
    ]
  },
  {
    "id": "skyreach",
    "name": "Skyreach",
    "summary": "Arrakoa citadel in the Spires of Arak. Deadly Solar Winds and feather mechanics require constant movement.",
    "bosses": [],
    "trash": []
  },
  {
    "id": "pit-of-saron",
    "name": "Pit of Saron",
    "summary": "Scourge mine beneath Icecrown Citadel. Ice shatters, icicle barrages and permafrost require tight coordination.",
    "bosses": [],
    "trash": []
  }
];
